package com.epam.project1.service;

public interface ISettings {

	double PRICE_COMPARATION_E = 0.01;
	
	int MAIN_MENU_ADD_GEM_NUMBER = 1;
	int MAIN_MENU_GEMS_WEIGHT_NUMBER = 2;
	int MAIN_MENU_GEMS_PRICE_NUMBER = 3;
	int MAIN_MENU_SORT_GEMS_NUMBER = 4;
	int MAIN_MENU_SELECT_GEMS_NUMBER = 5;
	int MAIN_MENU_LOAD_FILE_NUMBER = 6;
	int MAIN_MENU_SAVE_FILE_NUMBER = 7;
	int MAIN_MENU_CHANGE_LANGUAGE_NUMBER = 8;
	int MAIN_MENU_EXIT_NUMBER = 0;
	
	int CHANGE_LANGUAGE_MENU_ENGLISH_NUMBER = 1;
	int CHANGE_LANGUAGE_MENU_UKRAINIAN_NUMBER = 2;
}
